# Generated by Django 6.1 on 2026-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_unsafe_user_remove_post_author_unsafepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafe_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
