# Generated by Django 6.1 on 2026-08-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_unsafe_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unsafe_user',
            new_name='Unsafeuser',
        ),
    ]
